import Foundation

public struct PlanRenderer: Sendable {

    public init() {}

    public func renderMarkdown(_ plan: PlanDocument) -> String {
        var lines: [String] = []
        lines.append("# Implementation Plan: \(plan.projectName)")
        lines.append("> Generated by `apus plan` on \(plan.generatedAt)")
        lines.append("")

        if plan.overview != nil || plan.modules != nil {
            renderContext(&lines, plan)
        }

        if let tasks = plan.tasks, !tasks.isEmpty {
            if plan.overview != nil || plan.modules != nil {
                lines.append("---")
                lines.append("")
            }
            renderTasks(&lines, tasks)
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Context

    private func renderContext(_ lines: inout [String], _ plan: PlanDocument) {
        lines.append("## Codebase Context")
        lines.append("")

        if let overview = plan.overview {
            renderOverview(&lines, overview)
        }

        if let modules = plan.modules, !modules.isEmpty {
            renderModules(&lines, modules)
        }

        if let protocols = plan.protocolRelationships, !protocols.isEmpty {
            renderProtocols(&lines, protocols)
        }

        if let entryPoints = plan.entryPoints, !entryPoints.isEmpty {
            renderEntryPoints(&lines, entryPoints)
        }
    }

    private func renderOverview(_ lines: inout [String], _ overview: ProjectOverview) {
        lines.append("### Overview")
        lines.append("")
        lines.append("| Metric | Count |")
        lines.append("|--------|------:|")
        lines.append("| Targets | \(overview.targetCount) |")
        lines.append("| Files | \(overview.fileCount) |")
        lines.append("| Symbols | \(overview.symbolCount) |")
        lines.append("| Edges | \(overview.edgeCount) |")
        lines.append("")

        if !overview.topKinds.isEmpty {
            lines.append("**Symbols by kind:** " + overview.topKinds.map { "\($0.count) \($0.kind)s" }.joined(separator: ", "))
            lines.append("")
        }
    }

    private func renderModules(_ lines: inout [String], _ modules: [ModuleEntry]) {
        lines.append("### Modules")
        lines.append("")

        for module in modules {
            lines.append("#### \(module.name)")
            lines.append("")
            lines.append("- **Symbols:** \(module.symbolCount) (\(module.publicAPICount) public)")
            lines.append("- **Files:** \(module.fileCount)")
            if !module.dependsOn.isEmpty {
                lines.append("- **Depends on:** \(module.dependsOn.joined(separator: ", "))")
            }
            if !module.dependedOnBy.isEmpty {
                lines.append("- **Depended on by:** \(module.dependedOnBy.joined(separator: ", "))")
            }

            if !module.keyTypes.isEmpty {
                lines.append("- **Key types:**")
                for kt in module.keyTypes {
                    var location = ""
                    if let path = kt.filePath, let line = kt.line {
                        location = " (`\(shortenPath(path)):\(line)`)"
                    }
                    let conformances = kt.conformsTo.isEmpty ? "" : " [conforms to: \(kt.conformsTo.joined(separator: ", "))]"
                    lines.append("  - `\(kt.name)` (\(kt.kind), \(kt.incomingEdges + kt.outgoingEdges) edges)\(location)\(conformances)")
                }
            }
            lines.append("")
        }

        // Module dependency graph
        let deps = modules.flatMap { m in m.dependsOn.map { (m.name, $0) } }
        if !deps.isEmpty {
            lines.append("### Module Dependency Graph")
            lines.append("")
            lines.append("```")
            for (src, dst) in deps {
                lines.append("\(src) \u{2192} \(dst)")
            }
            lines.append("```")
            lines.append("")
        }
    }

    private func renderProtocols(_ lines: inout [String], _ protocols: [ProtocolRelationship]) {
        lines.append("### Type Relationships")
        lines.append("")
        for rel in protocols.prefix(20) {
            lines.append("- **\(rel.protocolName)**: \(rel.conformers.joined(separator: ", "))")
        }
        lines.append("")
    }

    private func renderEntryPoints(_ lines: inout [String], _ entryPoints: [KeyTypeEntry]) {
        lines.append("### Entry Points & Public API")
        lines.append("")
        lines.append("| Type | Kind | Edges | Location |")
        lines.append("|------|------|------:|----------|")
        for ep in entryPoints {
            let location: String
            if let path = ep.filePath, let line = ep.line {
                location = "`\(shortenPath(path)):\(line)`"
            } else {
                location = "-"
            }
            lines.append("| \(ep.name) | \(ep.kind) | \(ep.incomingEdges + ep.outgoingEdges) | \(location) |")
        }
        lines.append("")
    }

    // MARK: - Tasks

    private func renderTasks(_ lines: inout [String], _ tasks: [ImprovementTask]) {
        lines.append("## Improvement Tasks")
        lines.append("")

        let grouped: [(String, [ImprovementTask])] = [
            ("High Priority", tasks.filter { $0.priority == .high }),
            ("Medium Priority", tasks.filter { $0.priority == .medium }),
            ("Low Priority", tasks.filter { $0.priority == .low }),
        ]

        for (heading, group) in grouped where !group.isEmpty {
            lines.append("### \(heading)")
            lines.append("")
            for (i, task) in group.enumerated() {
                lines.append("#### \(i + 1). \(task.title)")
                lines.append("")
                lines.append("**Category:** \(task.category) | **Impact:** \(task.impactMetric)")
                lines.append("")
                lines.append(task.description)
                lines.append("")

                if !task.affectedFiles.isEmpty {
                    lines.append("**Affected files:**")
                    for ref in task.affectedFiles {
                        var entry = "- `\(shortenPath(ref.path))`"
                        if let line = ref.line { entry += ":\(line)" }
                        if let sym = ref.symbolName { entry += " (\(sym))" }
                        lines.append(entry)
                    }
                    lines.append("")
                }

                lines.append("**Suggested approach:** \(task.suggestedApproach)")
                lines.append("")
            }
        }
    }

    // MARK: - Helpers

    private func shortenPath(_ path: String) -> String {
        let components = path.split(separator: "/")
        if components.count > 3 {
            return ".../" + components.suffix(3).joined(separator: "/")
        }
        return path
    }
}
